"""initial schema

Every table from PRD "Data Model", plus the Phase 1 deltas: Service.container_port
(D1), Deployment.error_message, Instance.stopped_at, and the Domain table (D15)
with its CHECK constraint.

Hand-written rather than autogenerated — there was no live Postgres to diff
against when it was authored. Run `alembic check` after the first
`alembic upgrade head` to prove it matches the models.

Revision ID: 0001
Revises:
Create Date: 2026-07-23
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Enum member VALUES, not names — see pg_enum() in models/base.py.
SERVICE_KIND = sa.Enum("app", "database", "static", name="service_kind")
NODE_STATUS = sa.Enum("healthy", "unreachable", "draining", name="node_status")
DEPLOYMENT_STATUS = sa.Enum(
    "queued", "building", "deploying", "live", "failed", "superseded",
    name="deployment_status",
)
INSTANCE_STATUS = sa.Enum(
    "starting", "healthy", "unhealthy", "draining", "stopped", name="instance_status"
)
DOMAIN_TARGET_TYPE = sa.Enum("service", "deployment", name="domain_target_type")

TS = sa.DateTime(timezone=True)


def upgrade() -> None:
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", TS, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )

    op.create_table(
        "project",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", TS, nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "environment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("is_production", sa.Boolean(), nullable=False),
        sa.Column("wg_subnet", sa.String(length=32), nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_environment_project_name"),
    )

    op.create_table(
        "node",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("wg_public_key", sa.String(length=64), nullable=True),
        sa.Column("wg_ip", sa.String(length=45), nullable=True),
        sa.Column("cpu_total", sa.Float(), nullable=False),
        sa.Column("memory_total_mb", sa.Integer(), nullable=False),
        sa.Column("cpu_allocated", sa.Float(), nullable=False),
        sa.Column("memory_allocated_mb", sa.Integer(), nullable=False),
        sa.Column("status", NODE_STATUS, nullable=False),
        sa.Column("last_heartbeat_at", TS, nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hostname"),
    )

    op.create_table(
        "service",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("kind", SERVICE_KIND, nullable=False),
        sa.Column("source_repo", sa.String(length=255), nullable=True),
        sa.Column("source_branch", sa.String(length=255), nullable=False),
        sa.Column("dockerfile_path", sa.String(length=255), nullable=True),
        sa.Column("build_config", sa.JSON(), nullable=False),
        sa.Column("start_command", sa.String(length=512), nullable=True),
        sa.Column("container_port", sa.Integer(), nullable=False),
        sa.Column("health_check_path", sa.String(length=255), nullable=False),
        sa.Column("health_check_port", sa.Integer(), nullable=True),
        sa.Column("cpu_limit", sa.Float(), nullable=False),
        sa.Column("memory_limit_mb", sa.Integer(), nullable=False),
        sa.Column("replica_count", sa.Integer(), nullable=False),
        sa.Column("canvas_x", sa.Float(), nullable=False),
        sa.Column("canvas_y", sa.Float(), nullable=False),
        sa.Column("created_at", TS, nullable=False),
        sa.ForeignKeyConstraint(["environment_id"], ["environment.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("environment_id", "name", name="uq_service_environment_name"),
    )

    op.create_table(
        "variable",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("is_reference", sa.Boolean(), nullable=False),
        sa.Column("created_at", TS, nullable=False),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("service_id", "key", name="uq_variable_service_key"),
    )

    op.create_table(
        "volume",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("mount_path", sa.String(length=255), nullable=False),
        sa.Column("size_mb", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["node.id"]),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"]),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "deployment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("image_tag", sa.String(length=512), nullable=True),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("status", DEPLOYMENT_STATUS, nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("build_log_url", sa.String(length=512), nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("became_live_at", TS, nullable=True),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_deployment_status", "deployment", ["status"])

    op.create_table(
        "instance",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deployment_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("container_id", sa.String(length=64), nullable=True),
        sa.Column("status", INSTANCE_STATUS, nullable=False),
        sa.Column("wg_ip", sa.String(length=45), nullable=True),
        sa.Column("created_at", TS, nullable=False),
        sa.Column("started_at", TS, nullable=True),
        sa.Column("stopped_at", TS, nullable=True),
        sa.ForeignKeyConstraint(["deployment_id"], ["deployment.id"]),
        sa.ForeignKeyConstraint(["node_id"], ["node.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_instance_deployment_id", "instance", ["deployment_id"])
    op.create_index("ix_instance_status", "instance", ["status"])

    op.create_table(
        "domain",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", DOMAIN_TARGET_TYPE, nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("deployment_id", sa.Uuid(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("tls_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", TS, nullable=False),
        sa.ForeignKeyConstraint(["deployment_id"], ["deployment.id"]),
        sa.ForeignKeyConstraint(["environment_id"], ["environment.id"]),
        sa.ForeignKeyConstraint(["service_id"], ["service.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hostname"),
        # D15: exactly one target. Enforced here, not in application code.
        sa.CheckConstraint(
            "(service_id IS NOT NULL AND deployment_id IS NULL)"
            " OR (service_id IS NULL AND deployment_id IS NOT NULL)",
            name="ck_domain_exactly_one_target",
        ),
    )


def downgrade() -> None:
    op.drop_table("domain")
    op.drop_index("ix_instance_status", table_name="instance")
    op.drop_index("ix_instance_deployment_id", table_name="instance")
    op.drop_table("instance")
    op.drop_index("ix_deployment_status", table_name="deployment")
    op.drop_table("deployment")
    op.drop_table("volume")
    op.drop_table("variable")
    op.drop_table("service")
    op.drop_table("node")
    op.drop_table("environment")
    op.drop_table("project")
    op.drop_table("user")

    # drop_table does not drop the Postgres enum types it created.
    bind = op.get_bind()
    for enum_type in (
        DOMAIN_TARGET_TYPE,
        INSTANCE_STATUS,
        DEPLOYMENT_STATUS,
        SERVICE_KIND,
        NODE_STATUS,
    ):
        enum_type.drop(bind, checkfirst=True)
