"""add reported_state to node

Revision ID: b9a11d39f9d1
Revises: 0006
Create Date: 2026-07-24 18:16:52.870097
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b9a11d39f9d1'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('reported_state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'reported_state')
    # ### end Alembic commands ###
