#!/usr/bin/env bash
# Reset one *local development* Rudder installation to a known-empty state.
#
# This intentionally removes deployed release containers, their Docker Compose
# volumes/networks, the dev Postgres volume (which contains UI/API history),
# build logs, and generated Traefik routers. It never addresses Docker objects
# outside of the local Rudder project or Rudder's UUID-named release projects.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
compose_file="$repo_root/docker-compose.dev.yml"

if [[ ! -f "$compose_file" ]]; then
  echo "Could not find docker-compose.dev.yml from $repo_root" >&2
  exit 1
fi

is_release_project() {
  [[ "$1" =~ ^rudder-[0-9a-f]{8,}(-[0-9a-z-]+)?$ ]]
}

release_containers=()
while IFS= read -r container_id; do
  [[ -z "$container_id" ]] && continue
  project="$(docker inspect --format '{{ index .Config.Labels "com.docker.compose.project" }}' "$container_id")"
  if is_release_project "$project"; then
    release_containers+=("$container_id")
  fi
done < <(docker ps -aq --filter label=com.docker.compose.project)

if ((${#release_containers[@]})); then
  echo "Removing ${#release_containers[@]} Rudder release container(s)..."
  docker rm -f "${release_containers[@]}" >/dev/null
fi

release_volumes=()
while IFS= read -r volume_name; do
  [[ -z "$volume_name" ]] && continue
  project="$(docker volume inspect --format '{{ index .Labels "com.docker.compose.project" }}' "$volume_name")"
  if is_release_project "$project"; then
    release_volumes+=("$volume_name")
  fi
done < <(docker volume ls -q --filter label=com.docker.compose.project)

if ((${#release_volumes[@]})); then
  echo "Removing ${#release_volumes[@]} Rudder release volume(s)..."
  docker volume rm "${release_volumes[@]}" >/dev/null
fi

release_networks=()
while IFS= read -r network_id; do
  [[ -z "$network_id" ]] && continue
  project="$(docker network inspect --format '{{ index .Labels "com.docker.compose.project" }}' "$network_id")"
  if is_release_project "$project"; then
    release_networks+=("$network_id")
  fi
done < <(docker network ls -q --filter label=com.docker.compose.project)

if ((${#release_networks[@]})); then
  echo "Removing ${#release_networks[@]} Rudder release network(s)..."
  docker network rm "${release_networks[@]}" >/dev/null
fi

# Generated dynamic files are database-derived routes. Retaining one after the
# database reset would leave Traefik advertising a container that no longer
# exists. The header check leaves any hand-authored configuration untouched.
while IFS= read -r router_file; do
  [[ -z "$router_file" ]] && continue
  rm -f -- "$router_file"
done < <(grep -rl '^# Generated by Rudder ' "$repo_root/infra/traefik/dynamic" \
  --include='*.yml' --include='*.yaml' 2>/dev/null || true)

echo "Removing local control-plane data, build logs, and registry cache..."
docker compose -f "$compose_file" down --volumes --remove-orphans

echo "Starting a fresh local Rudder stack..."
docker compose -f "$compose_file" up -d

echo "Local Rudder history has been reset. Wait for the control plane and agent to become healthy before signing in."
